export const initialState = {
  type: "Section",
  pages: [
    {
      type: "Section",
      name: "Recomendaciones",
      description: "",
      pages: [
        {
          type: "Page",
          name: "Antes",
          description: "",
          content: [
            "Hay tareas que podemos realizar día a día, que pueden ayudar a reducir el riesgo en nuestras casas y en la comunidad. Te damos algunas recomendaciones para tener en cuenta:",
            "&1Prepará tu casa",
            [
              "Recogé la basura, escombros, ramas y hojas de tu casa para evitar que obstaculicen el paso del agua durante lluvias intensas y desborde de arroyos.",
              "Revisá  periódicamente  el  estado  de  techos,  canaletas,  rejillas  y  desagües  pluviales  de  tu  casa.  Sellá posibles filtraciones con algún material impermeable. ¡Importante! Tené especial cuida-do al eliminar cualquier tipo de elemento cortante que se acumule en techos, canaletas y desagües ya que puede ser arrastrado con el agua y lastimar a alguien.",
              "Colocá  todos  los  productos  peligrosos  o  tóxicos  (productos  de  limpieza,  combustibles,  ácidos,  venenos, desinfectantes, etc.) bien cerrados a una altura prudente donde no los alcance el agua en una eventual inundación, así evitamos el riesgo de contaminación. Cuidá que no se viertan combustibles, ácidos y solventes, ya que pueden producir daños en la salud, reacciones peligro-sas e incluso explosivas.",
              "Identificá qué muebles o ropa pueden verse afectados por el agua. Planificá cómo podrías ele-varlos en caso de precisarlo y de ser posible, adelantate y colocalos en un lugar alto, ¡te ahorrará mucha energía si hay una emergencia!",
            ],
            "&1Elaborá un plan de emergencia para tu vivienda",
            "Es importante que vos y todas/os en tu casa sepan cómo actuar en caso de emergencia. Por eso te recomendamos:",
            [
              "Asegurá que todas/os sepan cómo cortar los servicios de agua, luz y gas. ¡Será una de las prime-ras cosas que deberán hacer en caso de emergencia!",
              "Verificá  si  tu  casa  está  cerca  o  dentro  de  una  zona  con  riesgo  de  inundación,  esto  te  ayudará  a tomar conciencia de las medidas preventivas a seguir, entre ellas, identificar las zonas altas a donde dirigirse en caso de necesitarlo.",
              "Establecé un lugar seguro en la casa o acordá con una vecina/o cercano para acudir en caso de que  sea  necesario.  ¡Importante! Si  bien  debe  ser  evaluado  como  la  última  opción,  es  decir  en  caso de no tener la posibilidad de acudir a otro lugar seguro, es bueno saber dónde se encuentra el Punto de Encuentro más próximo, estos están disponibles para recibir y dar seguridad a las personas damnificadas.",
              "Establecé  un  plan  de  comunicación  para  mantener  el  contacto  familiar  en  caso  de  una  contingencia  y  asegurate  que  quede  en  un  lugar  visible  de  la  casa.  Designá  a  una  perso-na  a  quien  todas/os  puedan  llamar,  preferentemente  fuera  de  las  zonas  afectadas,  y  agendá  los  números  telefónicos  de  emergencia  (bomberos,  defensa  civil,  ambulancia,  seguridad).Sugerencia: avisá  a  una  misma  persona  el  lugar  donde  están  ubicados  y  el  estado  en  que  se  encuentran.",
              "Determiná prioridades de evacuación y resguardo para cualquier persona del hogar que tenga problemas de movilidad u otras necesidades especiales (niñas/os, adultas/os mayores, etc.)",
            ],
            "&1Resguardá toda la información y la documentación importante",
            "Colocá en una bolsa hermética y en un lugar seguro los documentos, partidas de nacimiento, libretas sanitarias, pasaportes, pólizas de seguros, escrituras y cualquier otro documento de valor. Todas las personas que viven en la casa deben conocer la ubicación de estos documentos para ponerlos a salvo.",
            "&1Armá un Kit de Emergencia",
            "Prepará  un  equipo  de  seguridad  que  puedas  tener  a  disposición  en  caso  de  emergencia.  Los  elementos básicos que debe contener son:",
            [
              "Agua potable embotellada",
              "Alimentos envasados o enlatados",
              "Linterna con pilas (repuesto de pilas)",
              "Radio a pilas (repuesto de pilas).",
              "Documentos y dinero (preferentemente guardarlos en bolsa impermeable).",
              "Muda seca de ropa interior, vestimenta básica y algún abrigo (preferentemente guardarla en bolsa impermeable).",
              "Medicamentos.",
              "Un botiquín de primeros auxilios.",
            ],
            "&2¿Qué debe contener el botiquín de primeros auxilios?",
            "El botiquín de primeros auxilios debe guardarse en un lugar fresco, seco, limpio, de fácil acceso y debe ubicarse lejos del alcance de las niñas y niños. Los elementos tienen que mantenerse en buen estado, deben controlarse sus fechas de vencimiento y reponerse periódicamente.",
            "&2Al menos debe incluir:",
            [
              "Guantes descartables de látex para no contaminar heridas.",
              "Gasas y vendas limpias (de 7 y 10 cm de ancho) para limpiar heridas y detener hemorragias.",
              "Apósitos estériles para limpiar y cubrir heridas abiertas.",
              "Cinta adhesiva para fijar gasas o vendajes.",
              "Tijera para cortar gasas y vendas.",
              "Antisépticos, yodo povidona, agua oxigenada (de 10 volúmenes) o alcohol para prevenir infecciones.",
              "Jabón neutro (blanco) para higienizar heridas.",
              "Alcohol en gel y líquido para higienizar las manos.",
            ],
            "Aclaración: no debe contener medicamentos.",
            "&1Cuidá la vía pública y los espacios verdes",
            [
              "Debemos tomar el hábito de mantener limpios todos los espacios que frecuentamos, es decir: no tirar basura al piso, a las zanjas o arroyos, sino hacerlo en los lugares permitidos; evitar la acumulación de escombros, residuos, etc. En caso de lluvias esto es fundamental para que el agua pueda drenar y tomar su curso natural.",
              "No saques los residuos durante las tormentas, ya que estos podrían obstruir el paso del agua. Es importante saber cuándo sacarlos ¡este pequeño hábito repercute en la salud de la ciudad! Aclaración: En el portal de la Municipalidad de La Plata encontrarás mapas con  días y horarios en los que pasa por tu barrio el recolector de cada tipo de residuos.",
              "Cuando estaciones tu auto no te olvides de dejar espacio suficiente entre el auto y el cordón de la  vereda  para  que  la  gente  que  se  encarga  de  mantener  limpia  la  ciudad  pueda  limpiar  esas  zonas y de esta manera no quede obstruido el paso del agua.",
              "Al estacionar un vehículo cerca de un contenedor de basura, dejá al menos un metro a cada lado del mismo para permitir la descarga al camión de basura.",
            ],
            "Podés avisar si se encuentran elementos que pueden obstruir las bocas de tormenta e impedir el fácil escurrimiento del agua. Es un llamado gratuito que puede hacerse al teléfono 147, Centro de Atención al Vecino (CAV) de la Municipalidad de La Plata, de lunes a viernes de 8 a 21 hs y los sábados de 8 a 13 hs",
            "&1Mantenete informado a través de los medios de comunicación oficiales",
            [
              "No propagues rumores o informaciones exageradas sobre la situación. Si te llega algún mensaje escrito o en audio por cualquier red social o servicio de mensajería, revisá las fuentes oficiales para corroborar la información. Debemos evitar el miedo y el caos que podrían provocar los falsos rumores.",
              "Dado  que  el  suministro  eléctrico  y  otras  redes  se  pueden  interrumpir  durante  una  tormenta  fuerte, contar con una radio a pilas puede garantizar el acceso a información oficial durante un evento.",
              "Mantenerse actualizado en cuanto al Plan General de Gestión de Riesgo Municipal es muy importante, identificando dónde se encuentran los Centros de Salud, Puntos de Encuentro, Delegaciones Municipales, Destacamentos de Bomberos, Comisarías y demás información necesaria para saber cómo se gestiona la emergencia en tu barrio y los centros de evacuación. Si no los conocés, podés consultar en el anexo de mapas de este manual o ingresar al portal web del Plan RRI en https://quehacerlaplata.org/",
            ],
            "&1Medio oficiales para recordar:",
            "Espacios de información del Servicio Meteorológico Nacional",
            "Página Web: https://www.smn.gob.ar/",
            "Facebook: https://www.facebook.com/SMN.ar/ ",
            "Instagram: https://www.instagram.com/smn_argentina/",
            "Twitter: https://twitter.com/smn_argentina/ ",
            "YouTube: https://www.youtube.com/user/SMNprensa",
            "Medios de comunicación de la MLP:",
            "Facebook de la Municipalidad: https://www.facebook.com/MunicipalidadDeLaPlata",
            "Facebook de Defensa Civil: https://www.facebook.com/Defensa-Civil-MLP-586965374704485/",
            "Twitter de Defensa Civil: https://twitter.com/defensacivilmlp",
            "Dial oficial de la Municipalidad de La Plata:FM 93.3",
            "Página Web de Radio Vértice: http://radiovertice.laplata.gob.ar/",
            "Twitter de la Dirección de Hidrometeorología de la Municipalidad de La Plata: https://twitter.com/climamlp",
            "App CLIMA MLP: Podes descargarte una aplicación a tu celular desde la tienda nube -desarrollada para Android y IOS- que informa sobre las precipitaciones y recomendaciones de Protección Civil.",
            "Números de teléfonos importantes:",
            "100 Bomberos",
            "103 Defensa Civil",
            "107 Ambulancia",
            "106 Prefectura",
            "147 Atención al vecino",
            "911 Seguridad",
          ],
        },
        { type: "Page", name: "Durante", description: "", content: [] },
        { type: "Page", name: "Después", description: "", content: [] },
      ],
    },
    {
      type: "Page",
      name: "Refugios",
      description: "",
      content: [""],
    },
  ],
};
